{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "aap-mock.fullname" . }}
  labels:
    {{- include "aap-mock.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "aap-mock.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}

