apiVersion: v1
kind: Service
metadata:
  name: aap-mock
  namespace: aap-mock
  labels:
    app: aap-mock
    app.kubernetes.io/name: aap-mock
    app.kubernetes.io/part-of: aap-mock
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: aap-mock

